name: app_mobile
description: "AI Virtual Assistant"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: any
  ultralytics_yolo: ^0.1.39
  flutter_launcher_icons: ^0.13.1



  image: ^4.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "/home/vophilong/Documents/Long_Tro_Ly_AO/Tro_Ly_Ao/app_mobile/assets/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/ai_button.jpg
#    - assets/model_face.tflite
#    - assets/model_face.txt